services:
  respec-team-registry:
    image: registry:latest
    ports:
      - 3209:5000
    environment:
      TZ: Asia/Seoul
    healthcheck:
      test: curl -kL --fail https://localhost:3209/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./auth/:/auth/
      - ./data/:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
    restart: always

  registry-web:
    image: joxit/docker-registry-ui:latest
    ports:
      - 3289:80
    environment:
      SINGLE_REGISTRY: true
      NGINX_PROXY_PASS_URL: https://respec.team:3209
      REGISTRY_TITLE: respec.team docker registry
      DELETE_IMAGES: true
      SHOW_CONTENT_DIGEST: true
    healthcheck:
      test: curl -L --fail http://localhost:3289/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - respec-team-registry
