services:
  mariadb:
    image: mariadb:latest
    expose:
      - 3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: resback
      MARIADB_PASSWORD_HASH: "*7C7FDBBF0DF5A71E0A0E9B553584BE1FCB410E26"
      MARIADB_DATABASE: resback
      MARIADB_MYSQL_LOCALHOST_USER: true
      TZ: Asia/Seoul
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  respec-team:
    image: respec.team:3209/respec-team
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Seoul
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - phpmyadmin_html:/var/www/html/:ro
    healthcheck:
      test: curl -kL --fail "https://localhost/" || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
    depends_on:
      - phpmyadmin
    restart: always

  resback:
    image: respec.team:3209/resback
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USERNAME: resback
      MYSQL_PASSWORD: kEH8A6SipKz0mFRCZ3MPjwOp1F4kfMw
      MYSQL_DATABASE: resback
      GOOGLE_REDIRECT_URI: https://respec.team/callbacks/google
      KAKAO_REDIRECT_URI: https://respec.team/callbacks/kakao
      NAVER_REDIRECT_URI: https://respec.team/callbacks/naver
      TZ: Asia/Seoul
    healthcheck:
      test: curl -L --fail "http://localhost:3000" || exit 1
      interval: 15s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    ports:
      - 9000:80
    environment:
      PMA_HOST: mariadb
      TZ: Asia/Seoul
    volumes:
      - phpmyadmin_html:/var/www/html/
    depends_on:
      - mariadb
    restart: always

volumes:
  phpmyadmin_html:
  frontend_html:
