services:
  mariadb:
    image: mariadb:latest
    expose:
      - 3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: resback
      MARIADB_PASSWORD_HASH: "*7C7FDBBF0DF5A71E0A0E9B553584BE1FCB410E26"
      MARIADB_DATABASE: resback
      MARIADB_MYSQL_LOCALHOST_USER: true
      TZ: Asia/Seoul
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - frontend_html:/usr/share/nginx/html/:ro
    healthcheck:
      test: curl -kL --fail "https://localhost/" || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
    depends_on:
      - phpmyadmin
      - respec-team
    restart: always

  respec-team:
    image: respec.team:3209/respec-team
    volumes:
      - frontend_html:/respec-team/

  resback:
    image: respec.team:3209/resback
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Seoul
    healthcheck:
      test: curl -kL --fail "https://localhost:3000" || exit 1
      interval: 15s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    ports:
      - 9000:80
    environment:
      PMA_HOST: mariadb
      TZ: Asia/Seoul
    volumes:
      - phpmyadmin_html:/var/www/html/
    depends_on:
      - mariadb
    restart: always

volumes:
  phpmyadmin_html:
  frontend_html:
