services:
  registry:
    image: registry:latest
    ports:
      - 3209:5000
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /etc/letsencrypt/live/respec.team/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /etc/letsencrypt/live/respec.team/privkey.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_DELETE_ENABLED: true
      TZ: Asia/Seoul
    healthcheck:
      test: curl -kL --fail https://localhost:3209/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./auth/:/auth/
    restart: always
